import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1746209537554 implements MigrationInterface {
    name = 'Initial1746209537554'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."invitations_status_enum" AS ENUM('pending', 'expired', 'canceled', 'accepted', 'rejected', 'archived')`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" SERIAL NOT NULL, "status" "public"."invitations_status_enum" NOT NULL DEFAULT 'pending', "email" character varying, "expired_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "recipient_id" uuid, "role_id" uuid, "sender_id" uuid, CONSTRAINT "UQ_4bd44ac953c17e8834a96028140" UNIQUE ("sender_id", "email", "status", "deleted_at"), CONSTRAINT "REL_bce12d652fbe682d912eda0bec" UNIQUE ("recipient_id"), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "role_id" uuid, "invitation_id" integer, CONSTRAINT "UQ_ed8ca8097af4eebf025bb099adb" UNIQUE ("name", "role_id", "invitation_id"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48ce552495d14eae9b187bb671" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "is_admin" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "role_id" uuid, "created_by" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying, "tax_number" character varying, "phone" character varying, "address" character varying, "city" character varying, "postalCode" character varying, "state" character varying, "country" character varying, "currency" character varying, "locale" character varying NOT NULL DEFAULT 'fr-FR', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid, CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."taxes_type_enum" AS ENUM('fixed', 'normal', 'inclusive', 'withholding', 'compound')`);
        await queryRunner.query(`CREATE TABLE "taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "rate" numeric(15,4) NOT NULL, "type" "public"."taxes_type_enum" NOT NULL, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "created_by" uuid, CONSTRAINT "UQ_04759969a5feeafb076a9a95a18" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_6c58c9cbb420c4f65e3f5eb8162" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, CONSTRAINT "UQ_4fe79d8197281f0baa3cb81a63b" UNIQUE ("company_id", "key", "deleted_at"), CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "number" character varying NOT NULL, "currency_code" character varying NOT NULL, "opening_balance" character varying NOT NULL, "bank_name" character varying, "bank_phone" character varying, "bank_address" character varying, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "created_by" uuid, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."categories_type_enum" AS ENUM('income', 'expense', 'item', 'other')`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying, "type" "public"."categories_type_enum" NOT NULL, "color" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "created_by" uuid, CONSTRAINT "UQ_c7368b8f1b3975b9af14344d555" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contacts_type_enum" AS ENUM('customer', 'supplier')`);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."contacts_type_enum" NOT NULL, "email" character varying, "taxNumber" character varying, "phone" character varying, "address" text, "city" character varying, "postal_code" character varying, "state" character varying, "country" character varying, "website" character varying, "currency_code" character varying, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "created_by" uuid, CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "articles_taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "article_id" uuid, "tax_id" uuid, CONSTRAINT "UQ_dd752236ffce39bb6675f41ea02" UNIQUE ("company_id", "article_id", "tax_id", "deleted_at"), CONSTRAINT "PK_05f4f7c97871530ae2774ba3336" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."articles_type_enum" AS ENUM('product', 'service')`);
        await queryRunner.query(`CREATE TABLE "articles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."articles_type_enum" NOT NULL, "sku" character varying, "description" text, "sale_price" numeric(15,4), "purchase_price" numeric(15,4), "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "category_id" uuid, "created_by" uuid, CONSTRAINT "UQ_3bc9a25fb2c89fd4d528ede5ca3" UNIQUE ("company_id", "sku", "deleted_at"), CONSTRAINT "PK_0a6e2c450d83e0b6052c2793334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."document_article_taxes_type_enum" AS ENUM('fixed', 'normal', 'inclusive', 'withholding', 'compound')`);
        await queryRunner.query(`CREATE TABLE "document_article_taxes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."document_article_taxes_type_enum" NOT NULL, "rate" numeric(15,4) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "document_article_id" uuid, "tax_id" uuid, "company_id" uuid, "created_by" uuid, CONSTRAINT "UQ_79277a7dc8ea242c2fe6cb4f587" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_e1fac4a547ae9b3a355edd52f23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."document_articles_type_enum" AS ENUM('product', 'service')`);
        await queryRunner.query(`CREATE TABLE "document_articles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."document_articles_type_enum" NOT NULL, "description" text, "sku" character varying, "quantity" numeric(12,2) NOT NULL, "price" numeric(15,4) NOT NULL, "tax" numeric(15,4) NOT NULL DEFAULT '0.0000', "discount_type" character varying NOT NULL DEFAULT 'normal', "discount_rate" numeric(15,4) NOT NULL DEFAULT '0.0000', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "document_id" uuid, "article_id" uuid, "company_id" uuid, "created_by" uuid, CONSTRAINT "UQ_503430f4814657973c4bf9763b5" UNIQUE ("name", "deleted_at"), CONSTRAINT "PK_ece8360f0fdffe4b8c1e40cfa68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."documents_type_enum" AS ENUM('invoice', 'bill')`);
        await queryRunner.query(`CREATE TYPE "public"."documents_status_enum" AS ENUM('draft', 'paid', 'partial', 'sent', 'received', 'viewed', 'cancelled', 'archived')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying NOT NULL, "order_number" character varying, "type" "public"."documents_type_enum" NOT NULL, "status" "public"."documents_status_enum" NOT NULL DEFAULT 'draft', "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL, "due_at" TIMESTAMP WITH TIME ZONE NOT NULL, "amount" numeric(15,4) NOT NULL, "currency_code" character varying NOT NULL, "currency_rate" numeric(15,8) NOT NULL, "contact_name" character varying NOT NULL, "contact_email" character varying, "contact_tax_number" character varying, "contact_phone" character varying, "contact_address" character varying, "contact_city" character varying, "contact_postal_code" character varying, "contact_state" character varying, "contact_country" character varying, "note" text, "footer" text, "title" character varying, "sub_title" character varying, "template" character varying, "color" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "contact_id" uuid, "category_id" uuid, "created_by" uuid, CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "amount" integer NOT NULL, "currency_code" character varying NOT NULL, "currency_rate" integer NOT NULL, "description" text, "reference" character varying, "paid_at" TIMESTAMP WITH TIME ZONE NOT NULL, "reconciled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "account_id" uuid, "document_id" uuid, "contact_id" uuid, "category_id" uuid, "created_by" uuid, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subject" character varying NOT NULL, "message" text NOT NULL, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "receiver_id" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."currencies_symbol_position_enum" AS ENUM('start', 'end')`);
        await queryRunner.query(`CREATE TABLE "currencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "symbol" character varying, "rate" numeric(15,8) NOT NULL, "precision" character varying, "symbol_position" "public"."currencies_symbol_position_enum" NOT NULL DEFAULT 'end', "decimal_mark" character varying, "thousands_separator" character varying, "disabled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "company_id" uuid, "created_by" uuid, CONSTRAINT "PK_d528c54860c4182db13548e08c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_bce12d652fbe682d912eda0bec8" FOREIGN KEY ("recipient_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_e4950c4d6aa2236f5213538e01a" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_9f63a5f4c5895a7be4d3f18ebe7" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_f10931e7bb05a3b434642ed2797" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0df723e214aa27bf7e5375d0cb1" FOREIGN KEY ("invitation_id") REFERENCES "invitations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f32b1cb14a9920477bcfd63df2c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_ca4df9b8772f1c1a02f3a560555" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD CONSTRAINT "FK_148b8a91a50f7847e042ecd8c13" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxes" ADD CONSTRAINT "FK_665b2073aea3c6c56f8522f7b3d" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settings" ADD CONSTRAINT "FK_3dc0f88c481ee12c88efbdafb0c" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_b22c8136b3e83352b0013224801" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_6ce484b7743042752cdecc41c99" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_987f987126a3f2e4f9ec03db04e" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_23ad9291e0e22cdf46ae7ec5461" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_b53945f3dfe982678bfeb5e1b4f" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_06dcbcd88c5647753f0f0a4f1cc" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles_taxes" ADD CONSTRAINT "FK_c14cec7699accd546c48f1e1503" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles_taxes" ADD CONSTRAINT "FK_fa8caab5a66412167c84cf28f7d" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles_taxes" ADD CONSTRAINT "FK_df231adf0e0186193d77fbd123d" FOREIGN KEY ("tax_id") REFERENCES "taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_9603a03397c48b0c1f6a553e072" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_e025eeefcdb2a269c42484ee43f" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_93c112ea984ff2e43deaa5dd202" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" ADD CONSTRAINT "FK_7c522a952d76c5c2aed4247b568" FOREIGN KEY ("document_article_id") REFERENCES "document_articles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" ADD CONSTRAINT "FK_e7858008d154963dad0b2086a62" FOREIGN KEY ("tax_id") REFERENCES "taxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" ADD CONSTRAINT "FK_6d647a674246fe8605b2ad42057" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" ADD CONSTRAINT "FK_b1c3e571f6329afde73bad2222f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_articles" ADD CONSTRAINT "FK_df141dd06744a36b36e422161ef" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_articles" ADD CONSTRAINT "FK_ebb7eb76835fd14e30c94c1646d" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_articles" ADD CONSTRAINT "FK_af5774213f66f9d5b983f1e9ba9" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_articles" ADD CONSTRAINT "FK_458f47c3e2a94a6ef788f8e8d13" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_7f9de69b9f75391dc280dd640fc" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_b906b2c3765fe7d0c87c7df4fab" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_b89e90c19762165e9647686650e" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_14371caaff44d0801b59b284166" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_8733562c5e54c31dd1ba8f49915" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_49c0d6e8ba4bfb5582000d851f0" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_cb19588501d3c1baec29708c805" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_ed668ff44e507caacb090e57e5e" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_77e84561125adeccf287547f66e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_343c8ee2cd2f4036f2a3423989e" FOREIGN KEY ("receiver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currencies" ADD CONSTRAINT "FK_32cd9a977a9b7199fbc34db977e" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currencies" ADD CONSTRAINT "FK_c999e1d171656df16e538737b94" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "currencies" DROP CONSTRAINT "FK_c999e1d171656df16e538737b94"`);
        await queryRunner.query(`ALTER TABLE "currencies" DROP CONSTRAINT "FK_32cd9a977a9b7199fbc34db977e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_343c8ee2cd2f4036f2a3423989e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_77e84561125adeccf287547f66e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_c9e41213ca42d50132ed7ab2b0f"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_ed668ff44e507caacb090e57e5e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_cb19588501d3c1baec29708c805"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_49c0d6e8ba4bfb5582000d851f0"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_8733562c5e54c31dd1ba8f49915"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_14371caaff44d0801b59b284166"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_b89e90c19762165e9647686650e"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_b906b2c3765fe7d0c87c7df4fab"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_7f9de69b9f75391dc280dd640fc"`);
        await queryRunner.query(`ALTER TABLE "document_articles" DROP CONSTRAINT "FK_458f47c3e2a94a6ef788f8e8d13"`);
        await queryRunner.query(`ALTER TABLE "document_articles" DROP CONSTRAINT "FK_af5774213f66f9d5b983f1e9ba9"`);
        await queryRunner.query(`ALTER TABLE "document_articles" DROP CONSTRAINT "FK_ebb7eb76835fd14e30c94c1646d"`);
        await queryRunner.query(`ALTER TABLE "document_articles" DROP CONSTRAINT "FK_df141dd06744a36b36e422161ef"`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" DROP CONSTRAINT "FK_b1c3e571f6329afde73bad2222f"`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" DROP CONSTRAINT "FK_6d647a674246fe8605b2ad42057"`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" DROP CONSTRAINT "FK_e7858008d154963dad0b2086a62"`);
        await queryRunner.query(`ALTER TABLE "document_article_taxes" DROP CONSTRAINT "FK_7c522a952d76c5c2aed4247b568"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_93c112ea984ff2e43deaa5dd202"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_e025eeefcdb2a269c42484ee43f"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_9603a03397c48b0c1f6a553e072"`);
        await queryRunner.query(`ALTER TABLE "articles_taxes" DROP CONSTRAINT "FK_df231adf0e0186193d77fbd123d"`);
        await queryRunner.query(`ALTER TABLE "articles_taxes" DROP CONSTRAINT "FK_fa8caab5a66412167c84cf28f7d"`);
        await queryRunner.query(`ALTER TABLE "articles_taxes" DROP CONSTRAINT "FK_c14cec7699accd546c48f1e1503"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_06dcbcd88c5647753f0f0a4f1cc"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_b53945f3dfe982678bfeb5e1b4f"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_23ad9291e0e22cdf46ae7ec5461"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_987f987126a3f2e4f9ec03db04e"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_6ce484b7743042752cdecc41c99"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_b22c8136b3e83352b0013224801"`);
        await queryRunner.query(`ALTER TABLE "settings" DROP CONSTRAINT "FK_3dc0f88c481ee12c88efbdafb0c"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP CONSTRAINT "FK_665b2073aea3c6c56f8522f7b3d"`);
        await queryRunner.query(`ALTER TABLE "taxes" DROP CONSTRAINT "FK_148b8a91a50f7847e042ecd8c13"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_ca4df9b8772f1c1a02f3a560555"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f32b1cb14a9920477bcfd63df2c"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_4a39f3095781cdd9d6061afaae5"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0df723e214aa27bf7e5375d0cb1"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_f10931e7bb05a3b434642ed2797"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_9f63a5f4c5895a7be4d3f18ebe7"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_e4950c4d6aa2236f5213538e01a"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_bce12d652fbe682d912eda0bec8"`);
        await queryRunner.query(`DROP TABLE "currencies"`);
        await queryRunner.query(`DROP TYPE "public"."currencies_symbol_position_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."documents_type_enum"`);
        await queryRunner.query(`DROP TABLE "document_articles"`);
        await queryRunner.query(`DROP TYPE "public"."document_articles_type_enum"`);
        await queryRunner.query(`DROP TABLE "document_article_taxes"`);
        await queryRunner.query(`DROP TYPE "public"."document_article_taxes_type_enum"`);
        await queryRunner.query(`DROP TABLE "articles"`);
        await queryRunner.query(`DROP TYPE "public"."articles_type_enum"`);
        await queryRunner.query(`DROP TABLE "articles_taxes"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP TYPE "public"."contacts_type_enum"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TYPE "public"."categories_type_enum"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "taxes"`);
        await queryRunner.query(`DROP TYPE "public"."taxes_type_enum"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48ce552495d14eae9b187bb671"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_status_enum"`);
    }

}
