FROM node:23-slim AS build

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

FROM node:23-slim

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package*.json ./
COPY --from=build --chmod=744 /usr/src/app/docker-entrypoint.sh ./docker-entrypoint.sh

ENV APP_ENV=production

ENTRYPOINT [ "./docker-entrypoint.sh" ]

EXPOSE 3000

CMD ["node", "dist/main"]
